/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import Controller.koneksi;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Anjayani
 */
public class dashboard extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public dashboard() {
        initComponents();
        btn_dashboard.setVisible(false);
        
        Connection conn = koneksi.getKoneksi();
ResultSet rs = null;
PreparedStatement pst = null;
       
    }
    
    
    
     void setHover(JPanel panel){
        panel.setBackground(new Color(53,33,89));
    }
    
    void resetHover (JPanel panel){
        panel.setBackground(new Color(255,255,255));
    }
    
  
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JPanel();
        btn_dashboard = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        hover_dashboard = new javax.swing.JPanel();
        bg_db = new javax.swing.JPanel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        hover_dashboard1 = new javax.swing.JPanel();
        btn_menu1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        hover_presensi = new javax.swing.JPanel();
        bg_mn1 = new javax.swing.JPanel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        hover_presensi1 = new javax.swing.JPanel();
        btn_menu2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        hover_karyawan = new javax.swing.JPanel();
        bg_mn2 = new javax.swing.JPanel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        hover_karyawan1 = new javax.swing.JPanel();
        btn_menu3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        hover_jadwal = new javax.swing.JPanel();
        bg_mn3 = new javax.swing.JPanel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        hover_jadwal1 = new javax.swing.JPanel();
        btn_menu4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        hover_report = new javax.swing.JPanel();
        bg_mn4 = new javax.swing.JPanel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        hover_report1 = new javax.swing.JPanel();
        btn_menu5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        hover_setting = new javax.swing.JPanel();
        bg_mn5 = new javax.swing.JPanel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        hover_setting1 = new javax.swing.JPanel();
        btn_menu6 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        hover_logout = new javax.swing.JPanel();
        bg_mn6 = new javax.swing.JPanel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        hover_logout1 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        main = new javax.swing.JPanel();
        dashboard = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        presensi = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jLabel47 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel74 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        karyawan = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        jLabel83 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jadwal = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable7 = new javax.swing.JTable();
        jPanel11 = new javax.swing.JPanel();
        jLabel92 = new javax.swing.JLabel();
        jTextField22 = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        report = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTable8 = new javax.swing.JTable();
        jPanel12 = new javax.swing.JPanel();
        jLabel101 = new javax.swing.JLabel();
        jTextField26 = new javax.swing.JTextField();
        jComboBox3 = new javax.swing.JComboBox<>();
        setting = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jTextField21 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jPasswordField4 = new javax.swing.JPasswordField();
        jPasswordField3 = new javax.swing.JPasswordField();
        jLabel73 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menu.setBackground(new java.awt.Color(255, 255, 255));
        menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_dashboard.setBackground(new java.awt.Color(255, 255, 255));
        btn_dashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_dashboardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_dashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_dashboardMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_dashboardMousePressed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons2/icons8-home-30 (1).png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(82, 80, 80));
        jLabel4.setText("Dashboard");

        hover_dashboard.setBackground(new java.awt.Color(53, 33, 89));

        javax.swing.GroupLayout hover_dashboardLayout = new javax.swing.GroupLayout(hover_dashboard);
        hover_dashboard.setLayout(hover_dashboardLayout);
        hover_dashboardLayout.setHorizontalGroup(
            hover_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        hover_dashboardLayout.setVerticalGroup(
            hover_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout btn_dashboardLayout = new javax.swing.GroupLayout(btn_dashboard);
        btn_dashboard.setLayout(btn_dashboardLayout);
        btn_dashboardLayout.setHorizontalGroup(
            btn_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_dashboardLayout.createSequentialGroup()
                .addComponent(hover_dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addGap(28, 28, 28)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );
        btn_dashboardLayout.setVerticalGroup(
            btn_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_dashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(hover_dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        menu.add(btn_dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 260, 50));

        bg_db.setBackground(new java.awt.Color(255, 255, 255));
        bg_db.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bg_db.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bg_dbMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bg_dbMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bg_dbMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bg_dbMousePressed(evt);
            }
        });

        jLabel54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons_ungu/icons8-home-30 (2).png"))); // NOI18N

        jLabel55.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(53, 33, 89));
        jLabel55.setText("Dashboard");

        hover_dashboard1.setBackground(new java.awt.Color(53, 33, 89));

        javax.swing.GroupLayout hover_dashboard1Layout = new javax.swing.GroupLayout(hover_dashboard1);
        hover_dashboard1.setLayout(hover_dashboard1Layout);
        hover_dashboard1Layout.setHorizontalGroup(
            hover_dashboard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        hover_dashboard1Layout.setVerticalGroup(
            hover_dashboard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout bg_dbLayout = new javax.swing.GroupLayout(bg_db);
        bg_db.setLayout(bg_dbLayout);
        bg_dbLayout.setHorizontalGroup(
            bg_dbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg_dbLayout.createSequentialGroup()
                .addComponent(hover_dashboard1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel54)
                .addGap(28, 28, 28)
                .addComponent(jLabel55, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );
        bg_dbLayout.setVerticalGroup(
            bg_dbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel54, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bg_dbLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel55, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(hover_dashboard1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        menu.add(bg_db, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 260, 50));

        btn_menu1.setBackground(new java.awt.Color(255, 255, 255));
        btn_menu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_menu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_menu1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_menu1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_menu1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_menu1MousePressed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons2/icons8-attendance-30.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(82, 80, 80));
        jLabel6.setText("Presensi");

        hover_presensi.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout hover_presensiLayout = new javax.swing.GroupLayout(hover_presensi);
        hover_presensi.setLayout(hover_presensiLayout);
        hover_presensiLayout.setHorizontalGroup(
            hover_presensiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        hover_presensiLayout.setVerticalGroup(
            hover_presensiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout btn_menu1Layout = new javax.swing.GroupLayout(btn_menu1);
        btn_menu1.setLayout(btn_menu1Layout);
        btn_menu1Layout.setHorizontalGroup(
            btn_menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_menu1Layout.createSequentialGroup()
                .addComponent(hover_presensi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel5)
                .addGap(32, 32, 32)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );
        btn_menu1Layout.setVerticalGroup(
            btn_menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_menu1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(hover_presensi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        menu.add(btn_menu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 260, 50));

        bg_mn1.setBackground(new java.awt.Color(255, 255, 255));
        bg_mn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bg_mn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bg_mn1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bg_mn1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bg_mn1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bg_mn1MousePressed(evt);
            }
        });

        jLabel56.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons_ungu/icons8-attendance-30 (1).png"))); // NOI18N

        jLabel57.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(53, 33, 89));
        jLabel57.setText("Presensi");

        hover_presensi1.setBackground(new java.awt.Color(53, 33, 89));

        javax.swing.GroupLayout hover_presensi1Layout = new javax.swing.GroupLayout(hover_presensi1);
        hover_presensi1.setLayout(hover_presensi1Layout);
        hover_presensi1Layout.setHorizontalGroup(
            hover_presensi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        hover_presensi1Layout.setVerticalGroup(
            hover_presensi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout bg_mn1Layout = new javax.swing.GroupLayout(bg_mn1);
        bg_mn1.setLayout(bg_mn1Layout);
        bg_mn1Layout.setHorizontalGroup(
            bg_mn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg_mn1Layout.createSequentialGroup()
                .addComponent(hover_presensi1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel56)
                .addGap(32, 32, 32)
                .addComponent(jLabel57, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );
        bg_mn1Layout.setVerticalGroup(
            bg_mn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel56, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bg_mn1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel57, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(hover_presensi1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        menu.add(bg_mn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 260, 50));

        btn_menu2.setBackground(new java.awt.Color(255, 255, 255));
        btn_menu2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_menu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_menu2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_menu2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_menu2MousePressed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons2/icons8-employee-35.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(82, 80, 80));
        jLabel8.setText("Karyawan");

        hover_karyawan.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout hover_karyawanLayout = new javax.swing.GroupLayout(hover_karyawan);
        hover_karyawan.setLayout(hover_karyawanLayout);
        hover_karyawanLayout.setHorizontalGroup(
            hover_karyawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        hover_karyawanLayout.setVerticalGroup(
            hover_karyawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout btn_menu2Layout = new javax.swing.GroupLayout(btn_menu2);
        btn_menu2.setLayout(btn_menu2Layout);
        btn_menu2Layout.setHorizontalGroup(
            btn_menu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_menu2Layout.createSequentialGroup()
                .addComponent(hover_karyawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        btn_menu2Layout.setVerticalGroup(
            btn_menu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(hover_karyawan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_menu2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        menu.add(btn_menu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 260, 50));

        bg_mn2.setBackground(new java.awt.Color(255, 255, 255));
        bg_mn2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bg_mn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bg_mn2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bg_mn2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bg_mn2MousePressed(evt);
            }
        });

        jLabel58.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons_ungu/icons8-employee-35.png"))); // NOI18N

        jLabel59.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(53, 33, 89));
        jLabel59.setText("Karyawan");

        hover_karyawan1.setBackground(new java.awt.Color(53, 33, 89));

        javax.swing.GroupLayout hover_karyawan1Layout = new javax.swing.GroupLayout(hover_karyawan1);
        hover_karyawan1.setLayout(hover_karyawan1Layout);
        hover_karyawan1Layout.setHorizontalGroup(
            hover_karyawan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        hover_karyawan1Layout.setVerticalGroup(
            hover_karyawan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout bg_mn2Layout = new javax.swing.GroupLayout(bg_mn2);
        bg_mn2.setLayout(bg_mn2Layout);
        bg_mn2Layout.setHorizontalGroup(
            bg_mn2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg_mn2Layout.createSequentialGroup()
                .addComponent(hover_karyawan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel58)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jLabel59, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        bg_mn2Layout.setVerticalGroup(
            bg_mn2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel58, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(hover_karyawan1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bg_mn2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel59, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        menu.add(bg_mn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 260, 50));

        btn_menu3.setBackground(new java.awt.Color(255, 255, 255));
        btn_menu3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_menu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_menu3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_menu3MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_menu3MousePressed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons2/icons8-schedule-30.png"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(82, 80, 80));
        jLabel10.setText("Jadwal");

        hover_jadwal.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout hover_jadwalLayout = new javax.swing.GroupLayout(hover_jadwal);
        hover_jadwal.setLayout(hover_jadwalLayout);
        hover_jadwalLayout.setHorizontalGroup(
            hover_jadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        hover_jadwalLayout.setVerticalGroup(
            hover_jadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout btn_menu3Layout = new javax.swing.GroupLayout(btn_menu3);
        btn_menu3.setLayout(btn_menu3Layout);
        btn_menu3Layout.setHorizontalGroup(
            btn_menu3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_menu3Layout.createSequentialGroup()
                .addComponent(hover_jadwal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel9)
                .addGap(33, 33, 33)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );
        btn_menu3Layout.setVerticalGroup(
            btn_menu3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(hover_jadwal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_menu3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        menu.add(btn_menu3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 260, 50));

        bg_mn3.setBackground(new java.awt.Color(255, 255, 255));
        bg_mn3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bg_mn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bg_mn3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bg_mn3MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bg_mn3MousePressed(evt);
            }
        });

        jLabel60.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons_ungu/icons8-schedule-30 (1).png"))); // NOI18N

        jLabel61.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(53, 33, 89));
        jLabel61.setText("Jadwal");

        hover_jadwal1.setBackground(new java.awt.Color(53, 33, 89));

        javax.swing.GroupLayout hover_jadwal1Layout = new javax.swing.GroupLayout(hover_jadwal1);
        hover_jadwal1.setLayout(hover_jadwal1Layout);
        hover_jadwal1Layout.setHorizontalGroup(
            hover_jadwal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        hover_jadwal1Layout.setVerticalGroup(
            hover_jadwal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout bg_mn3Layout = new javax.swing.GroupLayout(bg_mn3);
        bg_mn3.setLayout(bg_mn3Layout);
        bg_mn3Layout.setHorizontalGroup(
            bg_mn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg_mn3Layout.createSequentialGroup()
                .addComponent(hover_jadwal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel60)
                .addGap(33, 33, 33)
                .addComponent(jLabel61, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );
        bg_mn3Layout.setVerticalGroup(
            bg_mn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel60, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(hover_jadwal1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bg_mn3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel61, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        menu.add(bg_mn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 260, 50));

        btn_menu4.setBackground(new java.awt.Color(255, 255, 255));
        btn_menu4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_menu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_menu4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_menu4MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_menu4MousePressed(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons2/icons8-document-30.png"))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(82, 80, 80));
        jLabel12.setText("Report");

        hover_report.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout hover_reportLayout = new javax.swing.GroupLayout(hover_report);
        hover_report.setLayout(hover_reportLayout);
        hover_reportLayout.setHorizontalGroup(
            hover_reportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        hover_reportLayout.setVerticalGroup(
            hover_reportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout btn_menu4Layout = new javax.swing.GroupLayout(btn_menu4);
        btn_menu4.setLayout(btn_menu4Layout);
        btn_menu4Layout.setHorizontalGroup(
            btn_menu4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_menu4Layout.createSequentialGroup()
                .addComponent(hover_report, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel11)
                .addGap(32, 32, 32)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
        );
        btn_menu4Layout.setVerticalGroup(
            btn_menu4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(hover_report, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        menu.add(btn_menu4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 260, 50));

        bg_mn4.setBackground(new java.awt.Color(255, 255, 255));
        bg_mn4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bg_mn4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bg_mn4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bg_mn4MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bg_mn4MousePressed(evt);
            }
        });

        jLabel62.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons_ungu/icons8-document-30 (1).png"))); // NOI18N

        jLabel63.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(53, 33, 89));
        jLabel63.setText("Report");

        hover_report1.setBackground(new java.awt.Color(53, 33, 89));

        javax.swing.GroupLayout hover_report1Layout = new javax.swing.GroupLayout(hover_report1);
        hover_report1.setLayout(hover_report1Layout);
        hover_report1Layout.setHorizontalGroup(
            hover_report1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        hover_report1Layout.setVerticalGroup(
            hover_report1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout bg_mn4Layout = new javax.swing.GroupLayout(bg_mn4);
        bg_mn4.setLayout(bg_mn4Layout);
        bg_mn4Layout.setHorizontalGroup(
            bg_mn4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg_mn4Layout.createSequentialGroup()
                .addComponent(hover_report1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel62)
                .addGap(32, 32, 32)
                .addComponent(jLabel63, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
        );
        bg_mn4Layout.setVerticalGroup(
            bg_mn4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel62, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(jLabel63, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(hover_report1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        menu.add(bg_mn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 260, 50));

        btn_menu5.setBackground(new java.awt.Color(255, 255, 255));
        btn_menu5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_menu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_menu5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_menu5MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_menu5MousePressed(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons2/icons8-setting-30.png"))); // NOI18N

        jLabel14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(82, 80, 80));
        jLabel14.setText("Setting");

        hover_setting.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout hover_settingLayout = new javax.swing.GroupLayout(hover_setting);
        hover_setting.setLayout(hover_settingLayout);
        hover_settingLayout.setHorizontalGroup(
            hover_settingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        hover_settingLayout.setVerticalGroup(
            hover_settingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout btn_menu5Layout = new javax.swing.GroupLayout(btn_menu5);
        btn_menu5.setLayout(btn_menu5Layout);
        btn_menu5Layout.setHorizontalGroup(
            btn_menu5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_menu5Layout.createSequentialGroup()
                .addComponent(hover_setting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel13)
                .addGap(31, 31, 31)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );
        btn_menu5Layout.setVerticalGroup(
            btn_menu5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(hover_setting, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_menu5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        menu.add(btn_menu5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 260, 50));

        bg_mn5.setBackground(new java.awt.Color(255, 255, 255));
        bg_mn5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bg_mn5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bg_mn5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bg_mn5MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bg_mn5MousePressed(evt);
            }
        });

        jLabel64.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons_ungu/icons8-setting-30 (1).png"))); // NOI18N

        jLabel65.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel65.setForeground(new java.awt.Color(53, 33, 89));
        jLabel65.setText("Setting");

        hover_setting1.setBackground(new java.awt.Color(53, 33, 89));

        javax.swing.GroupLayout hover_setting1Layout = new javax.swing.GroupLayout(hover_setting1);
        hover_setting1.setLayout(hover_setting1Layout);
        hover_setting1Layout.setHorizontalGroup(
            hover_setting1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        hover_setting1Layout.setVerticalGroup(
            hover_setting1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout bg_mn5Layout = new javax.swing.GroupLayout(bg_mn5);
        bg_mn5.setLayout(bg_mn5Layout);
        bg_mn5Layout.setHorizontalGroup(
            bg_mn5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg_mn5Layout.createSequentialGroup()
                .addComponent(hover_setting1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel64)
                .addGap(31, 31, 31)
                .addComponent(jLabel65, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );
        bg_mn5Layout.setVerticalGroup(
            bg_mn5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel64, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(hover_setting1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bg_mn5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel65, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        menu.add(bg_mn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 260, 50));

        btn_menu6.setBackground(new java.awt.Color(255, 255, 255));
        btn_menu6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_menu6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_menu6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_menu6MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_menu6MousePressed(evt);
            }
        });

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons2/icons8-shutdown-30.png"))); // NOI18N

        jLabel16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(82, 80, 80));
        jLabel16.setText("Log Out");

        hover_logout.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout hover_logoutLayout = new javax.swing.GroupLayout(hover_logout);
        hover_logout.setLayout(hover_logoutLayout);
        hover_logoutLayout.setHorizontalGroup(
            hover_logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        hover_logoutLayout.setVerticalGroup(
            hover_logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout btn_menu6Layout = new javax.swing.GroupLayout(btn_menu6);
        btn_menu6.setLayout(btn_menu6Layout);
        btn_menu6Layout.setHorizontalGroup(
            btn_menu6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_menu6Layout.createSequentialGroup()
                .addComponent(hover_logout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel15)
                .addGap(31, 31, 31)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );
        btn_menu6Layout.setVerticalGroup(
            btn_menu6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_menu6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(hover_logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        menu.add(btn_menu6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 260, 50));

        bg_mn6.setBackground(new java.awt.Color(255, 255, 255));
        bg_mn6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bg_mn6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bg_mn6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bg_mn6MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bg_mn6MousePressed(evt);
            }
        });

        jLabel66.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons_ungu/icons8-shutdown-30 (1).png"))); // NOI18N

        jLabel67.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel67.setForeground(new java.awt.Color(53, 33, 89));
        jLabel67.setText("Log Out");

        hover_logout1.setBackground(new java.awt.Color(53, 33, 89));

        javax.swing.GroupLayout hover_logout1Layout = new javax.swing.GroupLayout(hover_logout1);
        hover_logout1.setLayout(hover_logout1Layout);
        hover_logout1Layout.setHorizontalGroup(
            hover_logout1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        hover_logout1Layout.setVerticalGroup(
            hover_logout1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout bg_mn6Layout = new javax.swing.GroupLayout(bg_mn6);
        bg_mn6.setLayout(bg_mn6Layout);
        bg_mn6Layout.setHorizontalGroup(
            bg_mn6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg_mn6Layout.createSequentialGroup()
                .addComponent(hover_logout1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel66)
                .addGap(31, 31, 31)
                .addComponent(jLabel67, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );
        bg_mn6Layout.setVerticalGroup(
            bg_mn6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel66, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bg_mn6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel67, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(hover_logout1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        menu.add(bg_mn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 260, 50));

        jPanel13.setBackground(new java.awt.Color(53, 33, 89));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-user-70.png"))); // NOI18N
        jPanel13.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel18.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Raihan Achmad D.F");
        jPanel13.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        jLabel19.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Admin");
        jPanel13.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, 30));

        menu.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 90));

        getContentPane().add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 660));

        main.setBackground(new java.awt.Color(255, 255, 255));
        main.setLayout(new java.awt.CardLayout());

        dashboard.setBackground(new java.awt.Color(239, 239, 239));
        dashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(85, 65, 118));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Dashboard");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 34, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-home-48.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 23, -1, -1));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Form_Jpg/Rectangle 17.png"))); // NOI18N
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 64, 540, 30));

        dashboard.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 90));

        jPanel7.setBackground(new java.awt.Color(85, 65, 118));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(64, 43, 100)));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel36.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("Karyawan");
        jPanel7.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 72, 30));

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-employee-70.png"))); // NOI18N
        jPanel7.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 102, 80, 90));

        dashboard.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 170, 310, 310));

        jPanel8.setBackground(new java.awt.Color(85, 65, 118));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(64, 43, 100)));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel38.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("Admin");
        jPanel8.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 72, -1));

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-user-70.png"))); // NOI18N
        jPanel8.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 104, 80, 82));

        dashboard.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 310, 310));

        main.add(dashboard, "card2");

        presensi.setBackground(new java.awt.Color(239, 239, 239));
        presensi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(85, 65, 118));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Presensi");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 34, -1, -1));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-attendance-48.png"))); // NOI18N
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 23, -1, -1));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Form_Jpg/Rectangle 17.png"))); // NOI18N
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 64, 540, 30));

        presensi.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 90));

        jTable5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "NIK", "NAMA", "STATUS", "JABATAN", "TANGGAL"
            }
        ));
        jScrollPane5.setViewportView(jTable5);

        presensi.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 1040, 480));

        jLabel47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons3/icons8-delete-25.png"))); // NOI18N
        jLabel47.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel47MousePressed(evt);
            }
        });
        presensi.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 130, 30, 30));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(85, 65, 118)));

        jLabel74.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-search-15.png"))); // NOI18N

        jTextField4.setBorder(null);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel74)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel74, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        presensi.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 190, 30));

        jLabel45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons3/icons8-edit-25.png"))); // NOI18N
        jLabel45.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel45MousePressed(evt);
            }
        });
        presensi.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 130, 30, 30));

        jLabel46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons3/icons8-add-25.png"))); // NOI18N
        jLabel46.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel46MousePressed(evt);
            }
        });
        presensi.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 130, -1, 30));

        main.add(presensi, "card2");

        karyawan.setBackground(new java.awt.Color(239, 239, 239));
        karyawan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(85, 65, 118));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Karyawan");
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 34, -1, -1));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-employee-48.png"))); // NOI18N
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 23, -1, -1));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Form_Jpg/Rectangle 17.png"))); // NOI18N
        jPanel3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 64, 540, 30));

        karyawan.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 90));

        jTable6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "NIK", "NAMA", "JENIS KELAMIN", "JABATAN"
            }
        ));
        jScrollPane6.setViewportView(jTable6);

        karyawan.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 1040, 480));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(85, 65, 118)));

        jLabel83.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-search-15.png"))); // NOI18N

        jTextField14.setBorder(null);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel83)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField14, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel83, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        karyawan.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 190, 30));

        jLabel48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons3/icons8-delete-25.png"))); // NOI18N
        jLabel48.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel48MousePressed(evt);
            }
        });
        karyawan.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 130, 30, 30));

        jLabel49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons3/icons8-edit-25.png"))); // NOI18N
        jLabel49.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel49MousePressed(evt);
            }
        });
        karyawan.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 130, 30, 30));

        jLabel50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons3/icons8-add-25.png"))); // NOI18N
        jLabel50.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel50MousePressed(evt);
            }
        });
        karyawan.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 130, -1, 30));

        main.add(karyawan, "card2");

        jadwal.setBackground(new java.awt.Color(239, 239, 239));
        jadwal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(85, 65, 118));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Jadwal");
        jPanel4.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 34, -1, -1));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-schedule-48.png"))); // NOI18N
        jPanel4.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 23, -1, -1));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Form_Jpg/Rectangle 17.png"))); // NOI18N
        jPanel4.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 70, 540, 20));

        jadwal.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 90));

        jTable7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        jTable7.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "HARI", "TANGGAL", "STATUS"
            }
        ));
        jScrollPane7.setViewportView(jTable7);

        jadwal.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 1040, 480));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(85, 65, 118)));

        jLabel92.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-search-15.png"))); // NOI18N

        jTextField22.setBorder(null);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel92)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField22, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel92, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jTextField22, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jadwal.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 190, 30));

        jLabel51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons3/icons8-delete-25.png"))); // NOI18N
        jLabel51.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel51MousePressed(evt);
            }
        });
        jadwal.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 130, 30, 30));

        jLabel52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons3/icons8-edit-25.png"))); // NOI18N
        jLabel52.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel52MousePressed(evt);
            }
        });
        jadwal.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 130, 30, 30));

        jLabel53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons3/icons8-add-25.png"))); // NOI18N
        jLabel53.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel53MousePressed(evt);
            }
        });
        jadwal.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 130, -1, 30));

        main.add(jadwal, "card2");

        report.setBackground(new java.awt.Color(239, 239, 239));
        report.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(85, 65, 118));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Report");
        jPanel5.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 34, -1, -1));

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-document-48.png"))); // NOI18N
        jPanel5.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 23, -1, -1));

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Form_Jpg/Rectangle 17.png"))); // NOI18N
        jPanel5.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 70, 540, 20));

        report.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 90));

        jTable8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        jTable8.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "NO", "NIK", "NAMA", "STATUS", "JABATAN", "TANGGAL"
            }
        ));
        jScrollPane8.setViewportView(jTable8);

        report.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 1030, 480));

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(85, 65, 118)));

        jLabel101.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-search-15.png"))); // NOI18N

        jTextField26.setBorder(null);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel101)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField26, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel101, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jTextField26, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        report.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 190, 30));

        jComboBox3.setForeground(new java.awt.Color(82, 80, 80));
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        report.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 120, 160, 30));

        main.add(report, "card2");

        setting.setBackground(new java.awt.Color(239, 239, 239));
        setting.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(85, 65, 118));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel33.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Setting");
        jPanel6.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 34, -1, -1));

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-setting-48.png"))); // NOI18N
        jPanel6.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 23, -1, -1));

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Form_Jpg/Rectangle 17.png"))); // NOI18N
        jPanel6.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 70, 540, 20));

        setting.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 90));

        jTextField21.setBorder(null);
        setting.add(jTextField21, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, 210, 20));

        jTextField19.setBorder(null);
        setting.add(jTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 300, 210, 30));

        jPasswordField4.setBorder(null);
        setting.add(jPasswordField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 390, 220, 30));

        jPasswordField3.setBorder(null);
        setting.add(jPasswordField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 480, 220, 20));

        jLabel73.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Form_Jpg/10.PNG"))); // NOI18N
        setting.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, -1, -1));

        jLabel70.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Form_Jpg/8.PNG"))); // NOI18N
        setting.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, -1, -1));

        jLabel71.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Form_Jpg/9.PNG"))); // NOI18N
        setting.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 430, -1, -1));

        jLabel72.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons3/icons8-edit-25.png"))); // NOI18N
        jLabel72.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel72MousePressed(evt);
            }
        });
        setting.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 540, -1, -1));

        main.add(setting, "card2");

        getContentPane().add(main, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 1070, 660));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_dashboardMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dashboardMousePressed
        btn_dashboard.setVisible(false);
        
        btn_menu1.setVisible(true);
        btn_menu2.setVisible(true);
        btn_menu3.setVisible(true);
        btn_menu4.setVisible(true);
        btn_menu5.setVisible(true);
        btn_menu6.setVisible(true);
        
        
        
        
        
        
        setHover(hover_dashboard);
    
        
        resetHover(hover_presensi);
        resetHover(hover_karyawan);
        resetHover(hover_jadwal);
        resetHover(hover_report);
        resetHover(hover_setting);
        resetHover(hover_logout);
        
      
        
        
        main.removeAll();
        main.repaint();
        main.revalidate();
        
        main.add(dashboard);
        main.repaint();
        main.revalidate();
    }//GEN-LAST:event_btn_dashboardMousePressed

    private void btn_menu1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_menu1MousePressed
        btn_menu1.setVisible(false);
        
        
        btn_dashboard.setVisible(true);
        btn_menu2.setVisible(true);
        btn_menu3.setVisible(true);
        btn_menu4.setVisible(true);
        btn_menu5.setVisible(true);
        btn_menu6.setVisible(true);




        setHover(hover_presensi);

        resetHover(hover_dashboard);
        resetHover(hover_karyawan);
        resetHover(hover_jadwal);
        resetHover(hover_report);
        resetHover(hover_setting);
        resetHover(hover_logout);
        
      

        main.removeAll();
        main.repaint();
        main.revalidate();
        
        main.add(presensi);
        main.repaint();
        main.revalidate();
    }//GEN-LAST:event_btn_menu1MousePressed

    private void btn_menu2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_menu2MousePressed
        
        btn_menu2.setVisible(false);
        
        btn_dashboard.setVisible(true);
        btn_menu1.setVisible(true);
        btn_menu3.setVisible(true);
        btn_menu4.setVisible(true);
        btn_menu5.setVisible(true);
        btn_menu6.setVisible(true);


        
        setHover(hover_karyawan);

        
        resetHover(hover_dashboard);
        resetHover(hover_presensi);
        resetHover(hover_jadwal);
        resetHover(hover_report);
        resetHover(hover_setting);
        resetHover(hover_logout);
        
   

        main.removeAll();
        main.repaint();
        main.revalidate();
        
        main.add(karyawan);
        main.repaint();
        main.revalidate();
    }//GEN-LAST:event_btn_menu2MousePressed

    private void btn_menu3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_menu3MousePressed
        
        btn_menu3.setVisible(false);
        
        btn_dashboard.setVisible(true);
        btn_menu1.setVisible(true);
        btn_menu2.setVisible(true);
        btn_menu4.setVisible(true);
        btn_menu5.setVisible(true);
        btn_menu6.setVisible(true);
        
        
        
        
        
        
        setHover(hover_jadwal);

        
        resetHover(hover_dashboard);
        resetHover(hover_presensi);
        resetHover(hover_karyawan);
        resetHover(hover_report);
        resetHover(hover_setting);
        resetHover(hover_logout);
        
  

        main.removeAll();
        main.repaint();
        main.revalidate();
        
        main.add(jadwal);
        main.repaint();
        main.revalidate();
    }//GEN-LAST:event_btn_menu3MousePressed

    private void btn_menu4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_menu4MousePressed
        
        btn_menu4.setVisible(false);
        
        btn_dashboard.setVisible(true);
        btn_menu1.setVisible(true);
        btn_menu2.setVisible(true);
        btn_menu3.setVisible(true);
        btn_menu5.setVisible(true);
        btn_menu6.setVisible(true);
        
        
        
        
        
        
        
        setHover(hover_report);

        
        resetHover(hover_dashboard);
        resetHover(hover_presensi);
        resetHover(hover_karyawan);
        resetHover(hover_jadwal);
        resetHover(hover_setting);
        resetHover(hover_logout);
        
      

        main.removeAll();
        main.repaint();
        main.revalidate();
        
        main.add(report);
        main.repaint();
        main.revalidate();
    }//GEN-LAST:event_btn_menu4MousePressed

    private void btn_menu5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_menu5MousePressed
        
        btn_menu5.setVisible(false);
        
        btn_dashboard.setVisible(true);
        btn_menu1.setVisible(true);
        btn_menu2.setVisible(true);
        btn_menu3.setVisible(true);
        btn_menu4.setVisible(true);
        btn_menu6.setVisible(true);
        




        
        setHover(hover_setting);

        
        resetHover(hover_dashboard);
        resetHover(hover_presensi);
        resetHover(hover_karyawan);
        resetHover(hover_jadwal);
        resetHover(hover_report);
        resetHover(hover_logout);
        
     

        main.removeAll();
        main.repaint();
        main.revalidate();
        
        main.add(setting);
        main.repaint();
        main.revalidate();
    }//GEN-LAST:event_btn_menu5MousePressed

    private void btn_menu6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_menu6MousePressed

        
        btn_menu6.setVisible(false);
        
        btn_dashboard.setVisible(true);
        btn_menu1.setVisible(true);
        btn_menu2.setVisible(true);
        btn_menu3.setVisible(true);
        btn_menu4.setVisible(true);
        btn_menu5.setVisible(true);
        
        
        
        
        setHover(hover_logout);

        resetHover(hover_dashboard);
        resetHover(hover_presensi);
        resetHover(hover_karyawan);
        resetHover(hover_jadwal);
        resetHover(hover_report);
        resetHover(hover_setting);
        
        
   
        

        int dialogbtn = JOptionPane.YES_NO_OPTION;
        int dialogresult = JOptionPane.showConfirmDialog(this, "Anda Yakin Ingin Keluar?", "Warning", dialogbtn);

        if (dialogresult == 0){
            new login().setVisible(true);
            this.setVisible(false);

        }
        else {

        }
    }//GEN-LAST:event_btn_menu6MousePressed

    private void jLabel46MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel46MousePressed
       new edit_presensi().setVisible(true);
    }//GEN-LAST:event_jLabel46MousePressed

    private void jLabel47MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel47MousePressed
       int dialogbtn = JOptionPane.YES_NO_OPTION;
       int dialogresult = JOptionPane.showConfirmDialog(this, "Anda Yakin?", "Warning", dialogbtn);
    }//GEN-LAST:event_jLabel47MousePressed

    private void jLabel45MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel45MousePressed
      int dialogbtn = JOptionPane.YES_NO_OPTION;
       int dialogresult = JOptionPane.showConfirmDialog(this, "Anda Yakin?", "Warning", dialogbtn);
    }//GEN-LAST:event_jLabel45MousePressed

    private void jLabel72MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel72MousePressed
        int dialogbtn = JOptionPane.YES_NO_OPTION;
       int dialogresult = JOptionPane.showConfirmDialog(this, "Anda Yakin?", "Warning", dialogbtn);
    }//GEN-LAST:event_jLabel72MousePressed

    private void btn_dashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dashboardMouseEntered
        btn_dashboard.setBackground(new Color(239,239,239));
    }//GEN-LAST:event_btn_dashboardMouseEntered

    private void btn_menu1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_menu1MouseEntered
         btn_menu1.setBackground(new Color(239,239,239));
    }//GEN-LAST:event_btn_menu1MouseEntered

    private void btn_menu2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_menu2MouseEntered
       btn_menu2.setBackground(new Color(239,239,239));      
    }//GEN-LAST:event_btn_menu2MouseEntered

    private void btn_menu3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_menu3MouseEntered
       btn_menu3.setBackground(new Color(239,239,239));      
    }//GEN-LAST:event_btn_menu3MouseEntered

    private void btn_menu4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_menu4MouseEntered
       btn_menu4.setBackground(new Color(239,239,239));        
    }//GEN-LAST:event_btn_menu4MouseEntered

    private void btn_menu5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_menu5MouseEntered
       btn_menu5.setBackground(new Color(239,239,239));       
    }//GEN-LAST:event_btn_menu5MouseEntered

    private void btn_menu6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_menu6MouseEntered
       btn_menu6.setBackground(new Color(239,239,239));      
    }//GEN-LAST:event_btn_menu6MouseEntered

    private void btn_dashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dashboardMouseExited
btn_dashboard.setBackground(new Color(255,255,255));      
    }//GEN-LAST:event_btn_dashboardMouseExited

    private void btn_menu1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_menu1MouseExited
btn_menu1.setBackground(new Color(255,255,255));         
    }//GEN-LAST:event_btn_menu1MouseExited

    private void btn_menu2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_menu2MouseExited
btn_menu2.setBackground(new Color(255,255,255));            
    }//GEN-LAST:event_btn_menu2MouseExited

    private void btn_menu3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_menu3MouseExited
btn_menu3.setBackground(new Color(255,255,255));              
    }//GEN-LAST:event_btn_menu3MouseExited

    private void btn_menu4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_menu4MouseExited
btn_menu4.setBackground(new Color(255,255,255));            
    }//GEN-LAST:event_btn_menu4MouseExited

    private void btn_menu5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_menu5MouseExited
btn_menu5.setBackground(new Color(255,255,255));       
    }//GEN-LAST:event_btn_menu5MouseExited

    private void btn_menu6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_menu6MouseExited
btn_menu6.setBackground(new Color(255,255,255));         
    }//GEN-LAST:event_btn_menu6MouseExited

    private void btn_dashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dashboardMouseClicked
  
   
      
    }//GEN-LAST:event_btn_dashboardMouseClicked

    private void btn_menu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_menu1MouseClicked

        
    }//GEN-LAST:event_btn_menu1MouseClicked

    private void bg_dbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bg_dbMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bg_dbMouseClicked

    private void bg_dbMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bg_dbMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_bg_dbMouseEntered

    private void bg_dbMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bg_dbMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_bg_dbMouseExited

    private void bg_dbMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bg_dbMousePressed
       
    }//GEN-LAST:event_bg_dbMousePressed

    private void bg_mn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bg_mn1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bg_mn1MouseClicked

    private void bg_mn1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bg_mn1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_bg_mn1MouseEntered

    private void bg_mn1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bg_mn1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_bg_mn1MouseExited

    private void bg_mn1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bg_mn1MousePressed
        
        
    }//GEN-LAST:event_bg_mn1MousePressed

    private void bg_mn2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bg_mn2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_bg_mn2MouseEntered

    private void bg_mn2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bg_mn2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_bg_mn2MouseExited

    private void bg_mn2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bg_mn2MousePressed
          
    
    }//GEN-LAST:event_bg_mn2MousePressed

    private void bg_mn3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bg_mn3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_bg_mn3MouseEntered

    private void bg_mn3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bg_mn3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_bg_mn3MouseExited

    private void bg_mn3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bg_mn3MousePressed
        
  
    }//GEN-LAST:event_bg_mn3MousePressed

    private void bg_mn4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bg_mn4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_bg_mn4MouseEntered

    private void bg_mn4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bg_mn4MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_bg_mn4MouseExited

    private void bg_mn4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bg_mn4MousePressed
        

    }//GEN-LAST:event_bg_mn4MousePressed

    private void bg_mn5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bg_mn5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_bg_mn5MouseEntered

    private void bg_mn5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bg_mn5MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_bg_mn5MouseExited

    private void bg_mn5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bg_mn5MousePressed
    
    }//GEN-LAST:event_bg_mn5MousePressed

    private void bg_mn6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bg_mn6MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_bg_mn6MouseEntered

    private void bg_mn6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bg_mn6MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_bg_mn6MouseExited

    private void bg_mn6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bg_mn6MousePressed
         
    
    }//GEN-LAST:event_bg_mn6MousePressed

    private void jLabel48MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel48MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel48MousePressed

    private void jLabel49MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel49MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel49MousePressed

    private void jLabel50MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel50MousePressed
        new edit_karyawan().setVisible(true);
    }//GEN-LAST:event_jLabel50MousePressed

    private void jLabel51MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel51MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel51MousePressed

    private void jLabel52MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel52MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel52MousePressed

    private void jLabel53MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel53MousePressed
        new edit_jadwal().setVisible(true);
    }//GEN-LAST:event_jLabel53MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg_db;
    private javax.swing.JPanel bg_mn1;
    private javax.swing.JPanel bg_mn2;
    private javax.swing.JPanel bg_mn3;
    private javax.swing.JPanel bg_mn4;
    private javax.swing.JPanel bg_mn5;
    private javax.swing.JPanel bg_mn6;
    private javax.swing.JPanel btn_dashboard;
    private javax.swing.JPanel btn_menu1;
    private javax.swing.JPanel btn_menu2;
    private javax.swing.JPanel btn_menu3;
    private javax.swing.JPanel btn_menu4;
    private javax.swing.JPanel btn_menu5;
    private javax.swing.JPanel btn_menu6;
    private javax.swing.JPanel dashboard;
    private javax.swing.JPanel hover_dashboard;
    private javax.swing.JPanel hover_dashboard1;
    private javax.swing.JPanel hover_jadwal;
    private javax.swing.JPanel hover_jadwal1;
    private javax.swing.JPanel hover_karyawan;
    private javax.swing.JPanel hover_karyawan1;
    private javax.swing.JPanel hover_logout;
    private javax.swing.JPanel hover_logout1;
    private javax.swing.JPanel hover_presensi;
    private javax.swing.JPanel hover_presensi1;
    private javax.swing.JPanel hover_report;
    private javax.swing.JPanel hover_report1;
    private javax.swing.JPanel hover_setting;
    private javax.swing.JPanel hover_setting1;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JPasswordField jPasswordField4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTable6;
    private javax.swing.JTable jTable7;
    private javax.swing.JTable jTable8;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JPanel jadwal;
    private javax.swing.JPanel karyawan;
    private javax.swing.JPanel main;
    private javax.swing.JPanel menu;
    private javax.swing.JPanel presensi;
    private javax.swing.JPanel report;
    private javax.swing.JPanel setting;
    // End of variables declaration//GEN-END:variables
}
