/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import Controller.Koneksi;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author Anjayani
 */
public final class PopUp_Presensi extends javax.swing.JFrame {

	Connection con;
	PreparedStatement pst;
	ResultSet rs;

	/**
	 * Creates new form edit_presensi
	 */
	public PopUp_Presensi() {
		this.con = Koneksi.getKoneksi();
		initComponents();
		disableTextFields();
		getNIK();
		getData();
	}

	public void disableTextFields() {
		nama.disable();
		jabatan.disable();
	}

	public void getData() {
		try {
			String sql = "select tbk.nama, tbj.nama as jabatan from tb_karyawan as tbk join tb_jabatan as tbj on tbk.id_jabatan = tbj.id where tbk.id = " + nikbox.getSelectedItem();
			System.out.println(sql);
			pst = con.prepareStatement(sql);
			rs = pst.executeQuery();
			if (rs.next()) {
				nama.setText(rs.getString(1));
				jabatan.setText(rs.getString(2));
			}
		} catch (SQLException ex) {
		}
	}

	public void getNIK() {
		try {
			nikbox.removeAllItems();
			String sql = "select id from tb_karyawan";
			pst = con.prepareStatement(sql);
			rs = pst.executeQuery();
			while (rs.next()) {
				nikbox.addItem(rs.getString(1));
			}
		} catch (SQLException ex) {
		}
	}

	public void setData() {
		try {
			String sql = "insert into tb_detail_presensi values('" + (String) statusbox.getSelectedItem() + "', CURRENT_TIMESTAMP, 1," + nikbox.getSelectedItem() + ");";
			System.out.println(sql);
			pst = con.prepareStatement(sql);
			pst.executeUpdate();
		} catch (SQLException ex) {
		}
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                nikbox = new javax.swing.JComboBox<>();
                statusbox = new javax.swing.JComboBox<>();
                jabatanbox = new javax.swing.JComboBox<>();
                nama = new javax.swing.JTextField();
                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                jLabel4 = new javax.swing.JLabel();
                close = new javax.swing.JPanel();
                jLabel6 = new javax.swing.JLabel();
                ok = new javax.swing.JPanel();
                jLabel7 = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setUndecorated(true);

                jPanel1.setBackground(new java.awt.Color(255, 255, 255));
                jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                nikbox.setBackground(new java.awt.Color(255, 255, 255));
                nikbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
                nikbox.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
                        public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                        }
                        public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                                nikboxPopupMenuWillBecomeInvisible(evt);
                        }
                        public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
                        }
                });
                nikbox.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                nikboxActionPerformed(evt);
                        }
                });
                jPanel1.add(nikbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 210, 30));

                statusbox.setBackground(new java.awt.Color(255, 255, 255));
                statusbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hadir", "Alpa", "Sakit", "Izin" }));
                statusbox.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
                        public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                        }
                        public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                                statusboxPopupMenuWillBecomeInvisible(evt);
                        }
                        public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
                        }
                });
                statusbox.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                statusboxActionPerformed(evt);
                        }
                });
                jPanel1.add(statusbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 210, 30));

                jabatanbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
                jPanel1.add(jabatanbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 200, -1));

                nama.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
                nama.setForeground(new java.awt.Color(0, 0, 0));
                nama.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                nama.setBorder(null);
                nama.addFocusListener(new java.awt.event.FocusAdapter() {
                        public void focusGained(java.awt.event.FocusEvent evt) {
                                namaFocusGained(evt);
                        }
                        public void focusLost(java.awt.event.FocusEvent evt) {
                                namaFocusLost(evt);
                        }
                });
                nama.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                namaMouseClicked(evt);
                        }
                });
                jPanel1.add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 210, 30));

                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Form_Field/nik.PNG"))); // NOI18N
                jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

                jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Form_Field/nama.PNG"))); // NOI18N
                jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, -1, 80));

                jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Form_Field/status.PNG"))); // NOI18N
                jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, -1, 80));

                jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Form_Field/jabatan.PNG"))); // NOI18N
                jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, -1, 80));

                close.setBackground(new java.awt.Color(244, 67, 54));
                close.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mousePressed(java.awt.event.MouseEvent evt) {
                                closeMousePressed(evt);
                        }
                        public void mouseExited(java.awt.event.MouseEvent evt) {
                                closeMouseExited(evt);
                        }
                        public void mouseEntered(java.awt.event.MouseEvent evt) {
                                closeMouseEntered(evt);
                        }
                });

                jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
                jLabel6.setForeground(new java.awt.Color(255, 255, 255));
                jLabel6.setText("CLOSE");

                javax.swing.GroupLayout closeLayout = new javax.swing.GroupLayout(close);
                close.setLayout(closeLayout);
                closeLayout.setHorizontalGroup(
                        closeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(closeLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                closeLayout.setVerticalGroup(
                        closeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                );

                jPanel1.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 90, 30));

                ok.setBackground(new java.awt.Color(31, 177, 65));
                ok.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mousePressed(java.awt.event.MouseEvent evt) {
                                okMousePressed(evt);
                        }
                        public void mouseExited(java.awt.event.MouseEvent evt) {
                                okMouseExited(evt);
                        }
                        public void mouseEntered(java.awt.event.MouseEvent evt) {
                                okMouseEntered(evt);
                        }
                });

                jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
                jLabel7.setForeground(new java.awt.Color(255, 255, 255));
                jLabel7.setText("OK");
                jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                jLabel7MouseClicked(evt);
                        }
                });

                javax.swing.GroupLayout okLayout = new javax.swing.GroupLayout(ok);
                ok.setLayout(okLayout);
                okLayout.setHorizontalGroup(
                        okLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, okLayout.createSequentialGroup()
                                .addContainerGap(31, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                );
                okLayout.setVerticalGroup(
                        okLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                );

                jPanel1.add(ok, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 90, 30));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                );

                pack();
                setLocationRelativeTo(null);
        }// </editor-fold>//GEN-END:initComponents

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered
	    close.setBackground(new Color(219, 42, 29));
    }//GEN-LAST:event_closeMouseEntered

    private void closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseExited
	    close.setBackground(new Color(244, 67, 54));
    }//GEN-LAST:event_closeMouseExited

    private void okMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okMouseEntered
	    ok.setBackground(new Color(6, 152, 40));
    }//GEN-LAST:event_okMouseEntered

    private void okMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okMouseExited
	    ok.setBackground(new Color(31, 177, 65));
    }//GEN-LAST:event_okMouseExited

    private void namaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_namaMouseClicked

    }//GEN-LAST:event_namaMouseClicked

    private void namaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_namaFocusGained
	    if (nama.getText().equals("Masukkan Nama")) {
		    nama.setText("");
		    nama.setForeground(new Color(0, 0, 0));
	    }
    }//GEN-LAST:event_namaFocusGained

    private void namaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_namaFocusLost
	    if (nama.getText().equals("")) {
		    nama.setText("Masukkan Nama");
		    nama.setForeground(new Color(204, 204, 204));
	    }
    }//GEN-LAST:event_namaFocusLost

    private void closeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMousePressed
	    this.setVisible(false);
    }//GEN-LAST:event_closeMousePressed

        private void nikboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nikboxActionPerformed
		// TODO add your handling code here:
        }//GEN-LAST:event_nikboxActionPerformed

        private void nikboxPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_nikboxPopupMenuWillBecomeInvisible
		// TODO add your handling code here:
		getData();
        }//GEN-LAST:event_nikboxPopupMenuWillBecomeInvisible

        private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
		// TODO add your handling code here:
		this.setVisible(false);
		setData();
		Dashboard d = new Dashboard();
		d.tablePresensi();
        }//GEN-LAST:event_jLabel7MouseClicked

        private void statusboxPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_statusboxPopupMenuWillBecomeInvisible
		// TODO add your handling code here:
        }//GEN-LAST:event_statusboxPopupMenuWillBecomeInvisible

        private void statusboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusboxActionPerformed
		// TODO add your handling code here:
        }//GEN-LAST:event_statusboxActionPerformed

        private void okMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okMousePressed
		// TODO add your handling code here:
		this.setVisible(false);
        }//GEN-LAST:event_okMousePressed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(PopUp_Presensi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(PopUp_Presensi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(PopUp_Presensi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(PopUp_Presensi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new PopUp_Presensi().setVisible(true);
			}
		});
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JPanel close;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JComboBox<String> jabatanbox;
        private javax.swing.JTextField nama;
        private javax.swing.JComboBox<String> nikbox;
        private javax.swing.JPanel ok;
        private javax.swing.JComboBox<String> statusbox;
        // End of variables declaration//GEN-END:variables
}
